image: gitpod/workspace-full

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - redhat.java@0.79.1:6b7e84ce557ec199240ac0a9bf4572bd